# Gitpod configuration file
image: gitpod/workspace-full

tasks:
  - name: Setup Environment
    init: |
      # Install Java and Maven
      sudo apt update && sudo apt install -y openjdk-17-jdk maven
      # Verify installation
      java -version
      mvn -version

  - name: Run Tests
    command: |
      # Run tests on LambdaTest Cloud Selenium Grid
      mvn clean test

ports:
  - port: 4444
    onOpen: ignore

github:
  prebuilds:
    # Enable prebuilds for faster startup
    master: true
    branches: true
